# Install SST Dataset

In [2]:
pip install datasets

In [ ]:
from datasets import load_dataset

dataset_train = load_dataset('sst', split='train')
df_train = dataset_train.to_pandas()
df_train=df_train.drop(df_train.columns[[2,3]],axis=1)

dataset_test = load_dataset('sst', split='test')
df_test = dataset_test.to_pandas()
df_test=df_test.drop(df_test.columns[[2,3]],axis=1)

dataset_validate = load_dataset('sst', split='validation')
df_validate = dataset_validate.to_pandas()
df_validate=df_validate.drop(df_validate.columns[[2,3]],axis=1)


In [4]:
df_train

sentence    label
0     The Rock is destined to be the 21st Century 's...  0.69444
1     The gorgeously elaborate continuation of `` Th...  0.83333
2     Singer\/composer Bryan Adams contributes a sle...  0.62500
3     You 'd think by now America would have had eno...  0.50000
4                  Yet the act is still charming here .  0.72222
...                                                 ...      ...
8539                                    A real snooze .  0.11111
8540                                     No surprises .  0.22222
8541  We 've seen the hippie-turned-yuppie plot befo...  0.75000
8542  Her fans walked out muttering words like `` ho...  0.13889
8543                                In this case zero .  0.34722

[8544 rows x 2 columns]


> Preprocessing Dataset Labels



In [ ]:
import pandas as pd

for i in range(len(df_train.iloc[:,1])):
  if df_train.iloc[i,1] <= 0.2:
    df_train.iloc[i,1] = 0
  elif df_train.iloc[i,1] > 0.2 and df_train.iloc[i,1] <= 0.4:
    df_train.iloc[i,1] = 1
  elif df_train.iloc[i,1] > 0.4 and df_train.iloc[i,1] <= 0.6:
    df_train.iloc[i,1] = 2
  elif df_train.iloc[i,1] > 0.6 and df_train.iloc[i,1] <= 0.8:
    df_train.iloc[i,1] = 3
  elif df_train.iloc[i,1] > 0.8:
    df_train.iloc[i,1] = 4
df_train.iloc[:, 1] = df_train.iloc[:, 1].astype('int16')


In [6]:
df_train

sentence  label
0     The Rock is destined to be the 21st Century 's...      3
1     The gorgeously elaborate continuation of `` Th...      4
2     Singer\/composer Bryan Adams contributes a sle...      3
3     You 'd think by now America would have had eno...      2
4                  Yet the act is still charming here .      3
...                                                 ...    ...
8539                                    A real snooze .      0
8540                                     No surprises .      1
8541  We 've seen the hippie-turned-yuppie plot befo...      3
8542  Her fans walked out muttering words like `` ho...      0
8543                                In this case zero .      1

[8544 rows x 2 columns]

In [ ]:
import pandas as pd

for i in range(len(df_validate.iloc[:,1])):
  if df_validate.iloc[i,1] <= 0.2:
    df_validate.iloc[i,1] = 0
  elif df_validate.iloc[i,1] > 0.2 and df_validate.iloc[i,1] <= 0.4:
    df_validate.iloc[i,1] = 1
  elif df_validate.iloc[i,1] > 0.4 and df_validate.iloc[i,1] <= 0.6:
    df_validate.iloc[i,1] = 2
  elif df_validate.iloc[i,1] > 0.6 and df_validate.iloc[i,1] <= 0.8:
   df_validate.iloc[i,1] = 3
  elif df_validate.iloc[i,1] > 0.8:
    df_validate.iloc[i,1] = 4
df_validate.iloc[:, 1] = df_validate.iloc[:, 1].astype('int16')

In [8]:
df_validate

sentence  label
0     It 's a lovely film with lovely performances b...      3
1     No one goes unindicted here , which is probabl...      2
2     And if you 're not nearly moved to tears by a ...      3
3                      A warm , funny , engaging film .      4
4     Uses sharp humor and insight into human nature...      4
...                                                 ...    ...
1096  it seems to me the film is about the art of ri...      1
1097  It 's just disappointingly superficial -- a mo...      1
1098  The title not only describes its main characte...      1
1099  Sometimes it feels as if it might have been ma...      2
1100  Schaeffer has to find some hook on which to ha...      1

[1101 rows x 2 columns]

In [ ]:
import pandas as pd

for i in range(len(df_test.iloc[:,1])):
  if df_test.iloc[i,1] <= 0.2:
    df_test.iloc[i,1] = 0
  elif df_test.iloc[i,1] > 0.2 and df_test.iloc[i,1] <= 0.4:
    df_test.iloc[i,1] = 1
  elif df_test.iloc[i,1] > 0.4 and df_test.iloc[i,1] <= 0.6:
    df_test.iloc[i,1] = 2
  elif df_test.iloc[i,1] > 0.6 and df_test.iloc[i,1] <= 0.8:
    df_test.iloc[i,1] = 3
  elif df_test.iloc[i,1] > 0.8:
    df_test.iloc[i,1] = 4
df_test.iloc[:, 1] = df_test.iloc[:, 1].astype('int16')

In [10]:
df_test

sentence  label
0                        Effective but too-tepid biopic      2
1     If you sometimes like to go to the movies to h...      3
2     Emerges as something rare , an issue movie tha...      4
3     The film provides some great insight into the ...      2
4     Offers that rare combination of entertainment ...      4
...                                                 ...    ...
2205                  An imaginative comedy\/thriller .      3
2206                      ( A ) rare , beautiful film .      4
2207                 ( An ) hilarious romantic comedy .      4
2208                Never ( sinks ) into exploitation .      3
2209                        ( U ) nrelentingly stupid .      0

[2210 rows x 2 columns]

# Naive Bayes Implementaion


> Generating The Vocabulary from Corpus



In [11]:
# Combine all text data into a single string
all_text = ' '.join(df_train['sentence'])

# Split the text into lowercase words
words = all_text.lower().split()

# Create a set to store unique words (vocab)
vocab = set(words)

# Remove non alphanumeric characters
vocab = {word for word in vocab if any(char.isalnum() for char in word)}

# Use set comprehension to split strings and add the split parts to the set
delimiter = ","
vocab = {part.strip() for item in vocab for part in item.split(delimiter)}

delimiter = "-"
vocab = {part.strip() for item in vocab for part in item.split(delimiter)}

delimiter = "\\/"
vocab = {part.strip() for item in vocab for part in item.split(delimiter)}

delimiter = "."
vocab = {part.strip() for item in vocab for part in item.split(delimiter)}

delimiter = "'"
vocab = {part.strip() for item in vocab for part in item.split(delimiter)}

delimiter = "&"
vocab = {part.strip() for item in vocab for part in item.split(delimiter)}

# Remove single character strings
vocab = {word for word in vocab if len(word) > 1}

vocab = vocab - {""}

In [12]:
len(vocab)

15285

In [90]:
for i in range(200, 220):
  print(sorted(list(vocab))[i])

accept
acceptable
acceptance
accepting
accepts
access
accessibility
accessible
accident
accidental
acclaim
acclaimed
accommodate
accomodates
accompanied
accompanies
accompanying
accomplish
accomplished
accomplishes




> Implementation From Scratch



In [14]:
import numpy as np

class NaiveBayes:
    def train_naive_bayes(self, D, C, vocab):
        # Calculate P(c) terms
        Ndoc = len(D) # Number of documents in the dataset D
        logprior = {}  # A dictionary to store the log prior probabilities for each class p(c)
        loglikelihood = {}  # A nested dictionary to store the log likelihoods of each word given each class p(x/c)
        Nc = {}   # A dictionary to store the count of documents for each class
        bigdoc = {}  # A dictionary to store documents grouped by class

        # Calculate Nc
        for c in C:
            Nc[c] = 0
            bigdoc[c] = []

        for doc, cls in D:
            Nc[cls] += 1
            bigdoc[cls].append(doc)

        # Calculate log P(c) terms
        for c in C:
            logprior[c] = np.log(Nc[c] / Ndoc)

        # Calculate log P(w|c) terms
        for w in vocab:
            for c in C:
                count_w_c = sum(1 for doc in bigdoc[c] if w in doc.lower().split())
                if w not in loglikelihood:
                    loglikelihood[w] = {}
                # Calculate the loglikelihood using Laplace Smoothing
                loglikelihood[w][c] = np.log((count_w_c + 1) / (len(vocab) + sum(len(doc.lower().split()) for doc in bigdoc[c])))

        return logprior, loglikelihood

    def pred(self, X, logprior, loglikelihood, vocab, C):
        predictions = []
        for x in X:
            posteriors = []
            for c in C:
                posterior = logprior[c]
                for word in x.lower().split():
                    if word in vocab:
                        posterior += loglikelihood[word][c]
                posteriors.append(posterior)
            predicted_class = C[np.argmax(posteriors)]
            predictions.append(predicted_class)

        return predictions

# Convert DataFrame to the appropriate format
D = list(zip(df_train.iloc[:, 0], df_train.iloc[:, 1]))
C = np.array([0, 1, 2, 3, 4])
nb=NaiveBayes()
logprior, loglikelihood =nb.train_naive_bayes(D, C, vocab)


In [96]:
# Predict labels of test dataset
test=df_test['sentence']
predict=nb.pred(test,logprior,loglikelihood, vocab,C)
print("Predicted Labels:")
predict[0:10]

Predicted Labels:


[3, 3, 3, 3, 4, 2, 2, 3, 3, 3]

In [17]:
import numpy as np

def test_naive_bayes(testdoc, logprior, loglikelihood, C, V):
    best_c = None
    best_sum = float('-inf')

    for c in C:
        sum_c = logprior[c]
        for s in testdoc['sentence']:  # Iterating directly over the elements of testdoc
            words = s.lower().split()
            for word in words:
              if word in V:
                  sum_c += loglikelihood.get(word, {}).get(c, 0)  # Adding loglikelihood if word exists in the vocabulary

        if sum_c > best_sum:
            best_sum = sum_c
            best_c = c

    return best_c

# Example usage:
testdoc = df_test
best_c = test_naive_bayes(testdoc, logprior, loglikelihood, C, vocab)
print("Best class:", best_c)

Best class: 3




> Implementation With Scikit Learn



In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create a pipeline with CountVectorizer and MultinomialNB
pipeline = Pipeline([
    ('vectorizer', CountVectorizer(binary=False)), # Generate Vocab
    ('classifier', MultinomialNB(alpha=1.0)),  # Laplace smoothing
])

# Fit the pipeline to the training data
pipeline.fit(df_train.iloc[:, 0], df_train.iloc[:, 1])

# Extract vocabulary from CountVectorizer
vectorizer = pipeline.named_steps['vectorizer']
vocabulary = vectorizer.get_feature_names_out()

# Calculate log prior probabilities (log P(c))
Ndoc = len(df_train)
logprior2 = {}
for c in pipeline.classes_:
    Nc = (df_train.iloc[:, 1] == c).sum()
    logprior2[c] = np.log(Nc / Ndoc)

# Calculate log likelihoods (log P(w|c))
loglikelihood2 = {}
for c, class_index in enumerate(pipeline.classes_):
    class_count = pipeline.named_steps['classifier'].feature_count_[c]
    loglikelihood2[c] = {}
    for word_index, word in enumerate(vocabulary):
        word_count = class_count[word_index]
        loglikelihood2[c][word] = np.log((word_count + 1) / (class_count.sum() + len(vocabulary)))

In [94]:
# Assuming df_test contains the test data
test_data = df_test.iloc[:, 0]

# Use the trained pipeline to predict labels
predicted_labels = pipeline.predict(test_data)

# Print the predicted labels
print("Predicted Labels:", predicted_labels)

Predicted Labels: [1 3 3 ... 4 1 0]


In [21]:
best_c = test_naive_bayes(testdoc, logprior2, loglikelihood2, C, vocabulary)
print("Best class:", best_c)

Best class: 3


In [23]:
len(vocabulary)

15285

In [91]:
for i in range(200,220):
  print(vocabulary[i])

accept
acceptable
acceptance
accepting
accepts
access
accessibility
accessible
accident
accidental
acclaim
acclaimed
accommodate
accomodates
accompanied
accompanies
accompanying
accomplish
accomplished
accomplishes



# Confusion Matrix & Evaluation Metrics For Naive Bayes



> From Scratch



In [55]:
def confusion_matrix(y_true, y_pred, num_classes):
    matrix = np.zeros((num_classes, num_classes), dtype=int)
    for i in range(len(y_true)):
        matrix[y_true[i], y_pred[i]] += 1
    return matrix

def precision_recall_f1(conf_matrix):
    num_classes = conf_matrix.shape[0]
    precision = np.zeros(num_classes)
    recall = np.zeros(num_classes)
    f1_score = np.zeros(num_classes)
    for i in range(num_classes):
        true_positive = conf_matrix[i, i]
        false_positive = np.sum(conf_matrix[:, i]) - true_positive
        false_negative = np.sum(conf_matrix[i, :]) - true_positive

        precision[i] = true_positive / (true_positive + false_positive) if (true_positive + false_positive) > 0 else 0
        recall[i] = true_positive / (true_positive + false_negative) if (true_positive + false_negative) > 0 else 0

        f1_score[i] = 2 * (precision[i] * recall[i]) / (precision[i] + recall[i]) if (precision[i] + recall[i]) > 0 else 0

    macro_precision = np.mean(precision)
    macro_recall = np.mean(recall)
    macro_f1_score = np.mean(f1_score)

    return precision, recall, f1_score, macro_precision, macro_recall, macro_f1_score

In [56]:
num_classes = 5

conf_matrix = confusion_matrix(df_test.iloc[:, 1], predict, num_classes)
precision, recall, f1_score, macro_precision, macro_recall, macro_f1_score = precision_recall_f1(conf_matrix)

print("Naive Bayes Evaluation From Scratch:\n")
print("Confusion Matrix:")
print(conf_matrix)
print("\nPrecision per class:", precision)
print("Recall per class:", recall)
print("F1 Score per class:", f1_score)
print("\nMacro-averaged Precision:", macro_precision)
print("Macro-averaged Recall:", macro_recall)
print("Macro-averaged F1 Score:", macro_f1_score)

Naive Bayes Evaluation From Scratch:

Confusion Matrix:
[[ 37 183  19  39   1]
 [ 27 400  64 133   9]
 [ 10 156  42 168  13]
 [  5  88  38 332  47]
 [  5  41  15 238 100]]

Precision per class: [0.44047619 0.46082949 0.23595506 0.36483516 0.58823529]
Recall per class: [0.13261649 0.63191153 0.10796915 0.65098039 0.25062657]
F1 Score per class: [0.20385675 0.53297801 0.14814815 0.46760563 0.35149385]

Macro-averaged Precision: 0.41806623973926704
Macro-averaged Recall: 0.3548208260169034
Macro-averaged F1 Score: 0.34081647895536005




> Scikit Learn



In [28]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report

# Assuming labels are already in integer format
classes = [0, 1, 2, 3, 4]

# Align predictions and ground truth labels
predictions = predicted_labels
true_labels = df_test.iloc[:, 1]

# Calculate confusion matrix
conf_matrix = confusion_matrix(true_labels, predictions, labels=classes)

print("Naive Bayes Evaluation Scikit Learn:\n")
print("Confusion Matrix:")
print(conf_matrix)

# Calculate precision, recall, and F1-score per class
precision_per_class = precision_score(true_labels, predictions, average=None)
print("\nPrecision for each class:")
for i, class_label in enumerate(classes):
    print(f"Class {class_label}: {precision_per_class[i]}")

recall_per_class = recall_score(true_labels, predictions, average=None)
print("\nRecall for each class:")
for i, class_label in enumerate(classes):
    print(f"Class {class_label}: {recall_per_class[i]}")

f1_score_per_class = f1_score(true_labels, predictions, average=None)
print("\nF1-Score for each class:")
for i, class_label in enumerate(classes):
    print(f"Class {class_label}: {f1_score_per_class[i]}")

# Calculate macro-averaged precision, recall, and F1-score
macro_precision = precision_score(true_labels, predictions, average='macro')
macro_recall = recall_score(true_labels, predictions, average='macro')
macro_f1_score = f1_score(true_labels, predictions, average='macro')

# Print macro-averaged scores
print("\nMacro-averaged Precision:", macro_precision)
print("Macro-averaged Recall:", macro_recall)
print("Macro-averaged F1-score:", macro_f1_score)

Naive Bayes Evaluation Scikit Learn:

Confusion Matrix:
[[ 28 200  10  41   0]
 [ 22 415  57 127  12]
 [  8 154  34 181  12]
 [  2  88  39 340  41]
 [  2  39  12 259  87]]

Precision for each class:
Class 0: 0.45161290322580644
Class 1: 0.46316964285714285
Class 2: 0.2236842105263158
Class 3: 0.35864978902953587
Class 4: 0.5723684210526315

Recall for each class:
Class 0: 0.1003584229390681
Class 1: 0.655608214849921
Class 2: 0.08740359897172237
Class 3: 0.6666666666666666
Class 4: 0.21804511278195488

F1-Score for each class:
Class 0: 0.16422287390029328
Class 1: 0.5428384565075213
Class 2: 0.1256931608133087
Class 3: 0.46639231824417016
Class 4: 0.3157894736842105

Macro-averaged Precision: 0.41389699333828645
Macro-averaged Recall: 0.3456164032418666
Macro-averaged F1-score: 0.3229872566299008


# Logistic Regression Implementation
> Creating The Dictionary










In [77]:
dic = {}
sentences = df_train['sentence'].tolist()
for s in sentences:
  words = ['<S>'] + s.lower().split() + ['<E>']
  for w1, w2 in zip(words, words[1:]):
    bigram = (w1, w2)
    dic[bigram] = dic.get(bigram, 0) + 1
    del bigram, w1, w2
  del words

In [30]:
len(dic)

86500

In [81]:
count = 0
for key, value in dic.items():
    print(key, ':', value)
    count += 1
    if count == 10:
        break

('<S>', 'the') : 1016
('the', 'rock') : 8
('rock', 'is') : 1
('is', 'destined') : 1
('destined', 'to') : 4
('to', 'be') : 246
('be', 'the') : 28
('the', '21st') : 3
('21st', 'century') : 4
('century', "'s") : 1


In [32]:
# Create a dictionary to map each bi-gram to its index in the feature vector
stoi = {bi_gram: index for index, bi_gram in enumerate(dic)}

In [82]:
count = 0
for key, value in stoi.items():
    print(key, ':', value)
    count += 1
    if count == 10:
        break

('<S>', 'the') : 0
('the', 'rock') : 1
('rock', 'is') : 2
('is', 'destined') : 3
('destined', 'to') : 4
('to', 'be') : 5
('be', 'the') : 6
('the', '21st') : 7
('21st', 'century') : 8
('century', "'s") : 9




> Vectorizing Features



In [42]:
import numpy as np

# Function to convert a sentence to vector representation
def sentence_to_vector(sentence, bi_gram_to_index):
    words = ['<S>'] + sentence.lower().split() + ['<E>'] # Convert to lowercase and split into words
    bi_grams = list(zip(words, words[1:]))  # Create bi-grams
    vector = np.zeros(len(bi_gram_to_index), dtype=np.int16)  # Initialize the vector with zeros

    for bi_gram in bi_grams:
        if bi_gram in bi_gram_to_index:
            vector[bi_gram_to_index[bi_gram]] = 1  # Set the corresponding index to 1
    return vector

In [97]:
# Convert each sentence to a vector representation
feature_vectors = [sentence_to_vector(s, stoi) for s in df_train['sentence']]

# Convert the list of feature vectors to a NumPy array
feature_matrix_np = np.array(feature_vectors)

# Display the feature matrix
print("Feature Matrix:")
print(feature_matrix_np)

Feature Matrix:
[[1 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]]


In [98]:
test_vectors = [sentence_to_vector(s, stoi) for s in df_test['sentence']]

# Convert the list of test vectors to a NumPy array
test_matrix_np = np.array(test_vectors)

print("Test Matrix:")
print(test_matrix_np)

Test Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [47]:
len(feature_vectors)

8544

In [49]:
print(feature_matrix_np.shape)

(8544, 86500)



> Implementation From Scratch



In [ ]:
import numpy as np

class LogisticRegression():
    def __init__(self, n_iters=100, learning_rate=0.01):
        self.n_iters = n_iters
        self.learning_rate = learning_rate
        self.weights = None
        self.bias = None

    def softmax(self, x):
        exp_x = np.exp(x - np.max(x))  # Subtract the maximum value for numerical stability
        return exp_x / np.sum(exp_x, axis=1, keepdims=True)

    def compute_loss(self, y_true, y_pred):
        # Categorical cross-entropy
        epsilon = 1e-9
        num_samples = len(y_true)
        loss = -np.sum(y_true * np.log(y_pred + epsilon)) / num_samples
        del epsilon, num_samples
        return loss

    def feed_forward(self, X):
        z = np.dot(X, self.weights) + self.bias
        A = self.softmax(z)
        del z
        return A

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # init parameters
        self.weights = np.zeros((n_features, y.shape[1]))
        self.bias = np.zeros((1, y.shape[1]))

        # SGD optimization
        for _ in range(self.n_iters):
            print("iter:", _)
            shuffled_indices = np.random.permutation(n_samples)
            X_shuffled = X[shuffled_indices]
            y_shuffled = y[shuffled_indices]

            for i in range(n_samples):
                X_i = X_shuffled[[i], :]
                y_i = y_shuffled[[i], :]
                y_pred = self.feed_forward(X_i)

                # Compute gradients
                # Assuming Categorical Cross-Entropy Loss
                dz = y_pred - y_i   # dL/dz
                dw = np.dot(X_i.T, dz)  # dL/dw
                db = np.sum(dz, axis=0, keepdims=True) # dL/db

                # Update parameters
                self.weights -= self.learning_rate * dw
                self.bias -= self.learning_rate * db

            del shuffled_indices, X_shuffled, y_shuffled

    def predict(self, X):
        z = np.dot(X, self.weights) + self.bias
        y_predicted = self.softmax(z)
        y_predicted_cls = np.argmax(y_predicted, axis=1)
        return y_predicted_cls


num_classes = 5
input_size = feature_matrix_np.shape[1]

model = LogisticRegression(n_iters=100, learning_rate=0.01)
labels = df_train['label'].to_numpy()
labels = np.eye(num_classes)[labels]  # One-hot encode labels
model.fit(feature_matrix_np, labels)


predictions = model.predict(test_matrix_np)


In [83]:
predictions

array([3, 3, 1, ..., 3, 3, 1])

> Implementation with Scikit Learn LogisticRegression

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Fit vectorizer and transform the text data into numerical features
X_train = vectorizer.fit_transform(df_train['sentence'])

# Extract the labels
y_train = df_train['label']

# Initialize logistic regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train, y_train)

# Transform the test text data into numerical features
X_test = vectorizer.transform(df_test['sentence'])

# Predict on the test data
y_pred = model.predict(X_test)



> Implementation with Scikit Learn SGDClassifier



In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Initialize TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Fit vectorizer and transform the text data into numerical features
X_train = vectorizer.fit_transform(df_train['sentence'])
X_test = vectorizer.transform(df_test['sentence'])  # Transform, not fit_transform!

# Extract the labels
y_train = df_train['label']
y_test = df_test['label']  # Extract labels for test data

# Initialize the SGDClassifier
model = SGDClassifier(loss='log', max_iter=1000, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Predict on the test data
y_pred2 = model.predict(X_test)

# Confusion Matrix & Evaluation Metrics For Logistic Regression


> From Scratch



In [57]:
num_classes = 5

conf_matrix = confusion_matrix(df_test.iloc[:, 1], predictions, num_classes)
precision, recall, f1_score, macro_precision, macro_recall, macro_f1_score = precision_recall_f1(conf_matrix)

print("Logistic Regression Evaluation From Scratch:\n")
print("Confusion Matrix:")
print(conf_matrix)
print("\nPrecision per class:", precision)
print("Recall per class:", recall)
print("F1 Score per class:", f1_score)
print("\nMacro-averaged Precision:", macro_precision)
print("Macro-averaged Recall:", macro_recall)
print("Macro-averaged F1 Score:", macro_f1_score)

Logistic Regression Evaluation From Scratch:

Confusion Matrix:
[[ 36 141  38  51  13]
 [ 36 323 100 156  18]
 [ 20 144  67 141  17]
 [  6 101  61 275  67]
 [  9  54  44 184 108]]

Precision per class: [0.3364486  0.42332896 0.21612903 0.34076828 0.48430493]
Recall per class: [0.12903226 0.51026856 0.1722365  0.53921569 0.27067669]
F1 Score per class: [0.1865285  0.46275072 0.19170243 0.41761579 0.34726688]

Macro-averaged Precision: 0.3601959610617903
Macro-averaged Recall: 0.3242859404651309
Macro-averaged F1 Score: 0.3211728640572861




> Scikit Learn LogisticRegression



In [99]:
from sklearn.metrics import confusion_matrix
classes = [0, 1, 2, 3, 4]
conf_matrix = confusion_matrix(df_test['label'],y_pred, labels=classes)

print("Logistic Regression Evaluation of Scikit Learn LogisticRegression:\n")
print("Confusion Matrix:")
print(conf_matrix)

# Calculate accuracy
accuracy = accuracy_score(df_test['label'], y_pred)
print("Accuracy:", accuracy)

# Generate a classification report
print("Classification Report:")
print(classification_report(df_test['label'], y_pred))

Logistic Regression Evaluation of Scikit Learn LogisticRegression:

Confusion Matrix:
[[ 41 171  22  39   6]
 [ 26 373  88 136  10]
 [  8 166  50 153  12]
 [  4  96  48 317  45]
 [  5  31  14 227 122]]
Accuracy: 0.4085972850678733
Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.15      0.23       279
           1       0.45      0.59      0.51       633
           2       0.23      0.13      0.16       389
           3       0.36      0.62      0.46       510
           4       0.63      0.31      0.41       399

    accuracy                           0.41      2210
   macro avg       0.43      0.36      0.35      2210
weighted avg       0.43      0.41      0.38      2210





> Scikit Learn SGDClassifier



In [100]:
from sklearn.metrics import confusion_matrix
classes = [0, 1, 2, 3, 4]
conf_matrix = confusion_matrix(df_test['label'],y_pred2, labels=classes)

print("Logistic Regression Evaluation of Scikit Learn SGDClassifier:\n")
print("Confusion Matrix:")
print(conf_matrix)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred2)
print("Accuracy:", accuracy)

# Generate a classification report
print("Classification Report:")
print(classification_report(y_test, y_pred2))

Logistic Regression Evaluation of Scikit Learn SGDClassifier:

Confusion Matrix:
[[ 35 178  20  40   6]
 [ 22 382  74 142  13]
 [  8 167  43 159  12]
 [  3 100  41 322  44]
 [  4  31  14 228 122]]
Accuracy: 0.4090497737556561
Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.13      0.20       279
           1       0.45      0.60      0.51       633
           2       0.22      0.11      0.15       389
           3       0.36      0.63      0.46       510
           4       0.62      0.31      0.41       399

    accuracy                           0.41      2210
   macro avg       0.43      0.36      0.35      2210
weighted avg       0.42      0.41      0.38      2210

